[project]
name = "hfc-lyme-disease"
version = "0.1.0"
description = "Forecasting Lyme disease using TimeGPT."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dotenv>=0.9.9",
    "matplotlib>=3.10.1",
    "nixtla>=0.6.6",
    "polars>=1.29.0",
    "statsforecast>=2.0.1",
]
